ServerEvents.recipes(event => {
	event.remove({ id: 'deco_storage:storage_crafter_recipe' })
	function repack(container, packing, packed_container, override_unpacking_recipe_id, override_packing_recipe_id) {
		var p_container = 'deco_storage:' + packed_container
		var packing_recipe_id = p_container + '_recipe'
		var unpacking_recipe_id = p_container + '_undo_recipe'
		if (override_packing_recipe_id == 'clone') {
			override_packing_recipe_id = packed_container
		}

		event.shaped(p_container, [
			'iii',
			'iCi',
			'iii'
		], {
			i: packing,
			C: 'deco_storage:' + container
		}
		).id(override_packing_recipe_id != undefined ? 'deco_storage:' + override_packing_recipe_id : packing_recipe_id)
		event.shapeless('8x ' + packing,
			p_container
		).id(override_unpacking_recipe_id != undefined ? 'deco_storage:' + override_unpacking_recipe_id : unpacking_recipe_id).replaceIngredient(p_container, 'deco_storage:' + container)
	}
	//deco_storage hangar
	repack('hanger', 'minecraft:beetroot', 'hanging_beetroots')
	repack('hanger', 'minecraft:carrot', 'hanging_carrots')
	repack('hanger', 'minecraft:cod', 'hanging_cod')
	repack('hanger', 'minecraft:golden_carrot', 'hanging_golden_carrots')
	repack('hanger', 'minecraft:leather', 'hanging_leather')
	repack('hanger', 'minecraft:salmon', 'hanging_salmon')
	repack('hanger', 'minecraft:tropical_fish', 'hanging_tropical_fish')
	//deco_storage tray
	repack('empty_tray', 'minecraft:bricks', 'tray_with_bricks')
	repack('empty_tray', 'minecraft:copper_ingot', 'tray_with_copper_ingots', undefined, 'clone')
	repack('empty_tray', 'minecraft:deepslate_bricks', 'tray_with_deepslate_bricks')
	repack('empty_tray', 'minecraft:end_stone_bricks', 'tray_with_end_stone_bricks')
	repack('empty_tray', 'minecraft:gold_ingot', 'tray_with_gold_ingots', undefined, 'clone')
	repack('empty_tray', 'minecraft:iron_ingot', 'tray_with_iron_ingots', undefined, 'clone')
	repack('empty_tray', 'minecraft:mud_bricks', 'tray_with_mud_bricks')
	repack('empty_tray', 'minecraft:nether_bricks', 'tray_with_nether_bricks')
	repack('empty_tray', 'minecraft:polished_blackstone_bricks', 'tray_with_polished_blackstone_bricks')
	repack('empty_tray', 'minecraft:raw_copper_block', 'tray_with_raw_copper')
	repack('empty_tray', 'minecraft:raw_gold_block', 'tray_with_raw_gold')
	repack('empty_tray', 'minecraft:raw_iron_block', 'tray_with_raw_iron')
	repack('empty_tray', 'minecraft:red_nether_bricks', 'tray_with_red_nether_bricks')
	repack('empty_tray', 'minecraft:stone_bricks', 'tray_with_stone_bricks')
	repack('empty_tray', 'minecraft:egg', 'tray_with_eggs')
	//deco_storage basket
	repack('empty_basket', 'farmersdelight:onion', 'basket_with_onions')
	repack('empty_basket', 'farmersdelight:tomato', 'basket_with_tomatoes')
	repack('empty_basket', 'minecraft:apple', 'basket_with_apples')
	repack('empty_basket', 'minecraft:beetroot', 'basket_with_beetroots')
	repack('empty_basket', 'minecraft:brown_mushroom', 'basket_with_brown_mushrooms')
	repack('empty_basket', 'minecraft:carrot', 'basket_with_carrots')
	repack('empty_basket', 'minecraft:cod', 'basket_with_cod')
	repack('empty_basket', 'minecraft:cookie', 'basket_with_cookies')
	repack('empty_basket', 'minecraft:golden_carrot', 'basket_with_golden_carrots')
	repack('empty_basket', 'minecraft:poisonous_potato', 'basket_with_poisonous_potatoes')
	repack('empty_basket', 'minecraft:potato', 'basket_with_potatoes')
	repack('empty_basket', 'minecraft:red_mushroom', 'basket_with_red_mushrooms')
	repack('empty_basket', 'minecraft:salmon', 'basket_with_salmon')
	repack('empty_basket', 'minecraft:tropical_fish', 'basket_with_tropical_fish')
	//deco_storage crate
	repack('empty_crate', 'farmersdelight:cabbage', 'crate_with_cabbage')
	repack('empty_crate', 'farmersdelight:onion', 'crate_with_onions')
	repack('empty_crate', 'farmersdelight:rice', 'crate_with_rice')
	repack('empty_crate', 'farmersdelight:tomato', 'crate_with_tomatoes')
	repack('empty_crate', 'minecraft:amethyst_shard', 'crate_with_amethysts', undefined, 'clone')
	repack('empty_crate', 'minecraft:apple', 'crate_with_apples')
	repack('empty_crate', 'minecraft:beetroot', 'crate_with_beetroots')
	repack('empty_crate', 'minecraft:carrot', 'crate_with_carrots')
	repack('empty_crate', 'minecraft:charcoal', 'crate_with_charcoal', undefined, 'clone')
	repack('empty_crate', 'minecraft:coal', 'crate_with_coal', undefined, 'clone')
	repack('empty_crate', 'minecraft:diamond', 'crate_with_diamonds', undefined, 'clone')
	repack('empty_crate', 'minecraft:emerald', 'crate_with_emeralds', undefined, 'clone')
	repack('empty_crate', 'minecraft:glow_berries', 'crate_with_glowberries')
	repack('empty_crate', 'minecraft:golden_apple', 'crate_with_golden_apples')
	repack('empty_crate', 'minecraft:golden_carrot', 'crate_with_golden_carrots')
	repack('empty_crate', 'minecraft:hay_block', 'crate_with_hay', undefined, 'clone')
	repack('empty_crate', 'minecraft:melon', 'crate_with_melons')
	repack('empty_crate', 'minecraft:poisonous_potato', 'crate_with_poisonous_potatoes')
	repack('empty_crate', 'minecraft:potato', 'crate_with_potatoes')
	repack('empty_crate', 'minecraft:pumpkin', 'crate_with_pumpkins')
	repack('empty_crate', 'minecraft:quartz', 'crate_with_quartz', undefined, 'clone')
	repack('empty_crate', 'minecraft:raw_copper_block', 'crate_with_raw_copper')
	repack('empty_crate', 'minecraft:raw_gold_block', 'crate_with_raw_gold')
	repack('empty_crate', 'minecraft:raw_iron_block', 'crate_with_raw_iron')
	repack('empty_crate', 'minecraft:sweet_berries', 'crate_with_sweetberries')
	repack('empty_crate', 'minecraft:egg', 'crate_with_eggs')
	//deco_storage barrel
	repack('empty_barrel', 'farmersdelight:cabbage', 'barrel_with_cabbage')
	repack('empty_barrel', 'farmersdelight:onion', 'barrel_with_onions')
	repack('empty_barrel', 'farmersdelight:rice', 'barrel_with_rice')
	repack('empty_barrel', 'farmersdelight:tomato', 'barrel_with_tomatoes')
	repack('empty_barrel', 'minecraft:amethyst_shard', 'barrel_with_amethysts')
	repack('empty_barrel', 'minecraft:apple', 'barrel_with_apples')
	repack('empty_barrel', 'minecraft:beetroot', 'barrel_with_beetroots')
	repack('empty_barrel', 'minecraft:bricks', 'barrel_with_bricks')
	repack('empty_barrel', 'minecraft:cactus', 'barrel_with_cactuses', 'barrel_with_cactus_undo_recipe', 'barrel_with_cactus_recipe')
	repack('empty_barrel', 'minecraft:carrot', 'barrel_with_carrots')
	repack('empty_barrel', 'minecraft:charcoal', 'barrel_with_charcoal')
	repack('empty_barrel', 'minecraft:coal', 'barrel_with_coal')
	repack('empty_barrel', 'minecraft:cod', 'barrel_with_cod')
	repack('empty_barrel', 'minecraft:deepslate_bricks', 'barrel_with_deepslate_bricks')
	repack('empty_barrel', 'minecraft:diamond', 'barrel_with_diamonds')
	repack('empty_barrel', 'minecraft:emerald', 'barrel_with_emeralds')
	repack('empty_barrel', 'minecraft:end_stone_bricks', 'barrel_with_end_bricks')
	repack('empty_barrel', 'minecraft:glow_berries', 'barrel_with_glowberries', 'barrel_with_glow_berries_undo_recipe', 'barrel_with_glow_berries_recipe')
	repack('empty_barrel', 'minecraft:golden_apple', 'barrel_with_golden_apples')
	repack('empty_barrel', 'minecraft:golden_carrot', 'barrel_with_golden_carrots')
	repack('empty_barrel', 'minecraft:hay_block', 'barrel_with_hay')
	repack('empty_barrel', 'minecraft:melon', 'barrel_with_melons')
	repack('empty_barrel', 'minecraft:mud_bricks', 'barrel_with_mud_bricks')
	repack('empty_barrel', 'minecraft:nether_bricks', 'barrel_with_nether_bricks')
	repack('empty_barrel', 'minecraft:poisonous_potato', 'barrel_with_poisonous_potatoes')
	repack('empty_barrel', 'minecraft:polished_blackstone_bricks', 'barrel_with_polished_blackstone_bricks')
	repack('empty_barrel', 'minecraft:potato', 'barrel_with_potatoes')
	repack('empty_barrel', 'minecraft:pumpkin', 'barrel_with_pumpkins')
	repack('empty_barrel', 'minecraft:quartz', 'barrel_with_quartz')
	repack('empty_barrel', 'minecraft:raw_copper_block', 'barrel_with_raw_copper')
	repack('empty_barrel', 'minecraft:raw_gold_block', 'barrel_with_raw_gold')
	repack('empty_barrel', 'minecraft:raw_iron_block', 'barrel_with_raw_iron')
	repack('empty_barrel', 'minecraft:red_nether_bricks', 'barrel_with_red_nether_bricks')
	repack('empty_barrel', 'minecraft:salmon', 'barrel_with_salmon')
	repack('empty_barrel', 'minecraft:stone_bricks', 'barrel_with_stone_bricks')
	repack('empty_barrel', 'minecraft:sugar_cane', 'barrel_with_sugarcane', 'barrel_with_sugar_cane_undo_recipe', 'barrel_with_sugar_cane_recipe')
	repack('empty_barrel', 'minecraft:sweet_berries', 'barrel_with_sweetberries', 'barrel_with_sweet_berries_undo_recipe', 'barrel_with_sweet_berries_recipe')
	repack('empty_barrel', 'minecraft:tropical_fish', 'barrel_with_tropical_fish')
	repack('empty_barrel', 'minecraft:tuff_bricks', 'barrel_with_tuff_bricks')
	repack('empty_barrel', 'minecraft:egg', 'barrel_with_eggs')
})