name: Feature Request
description: "For requesting new features or improvements"
assignees: Lucky-56
labels:
  - bug
  - triage
body:
  - type: dropdown
    attributes:
      label: Modpack
      description: What modpack are you reporting for?
      options:
        - karton creëren
    validations:
      required: true

  - type: textarea
    attributes:
      label: Feature Description
      description: >
        Please describe the feature you would like to have changed / added.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree that you have done your due diligence and done the following
      options:
        - label: I have searched the issue tracker and confirmed that something similar has not been reported
          required: true
        - label: I have verified that I am using the latest version of the modpack
          required: true
