Platform.mods.kubejs.name = 'karton creëren'


StartupEvents.registry('block', event => {

	//create compressed
	// wood
	event.create('cogwheel_block')
		.parentModel('minecraft:block/cube_bottom_top')
		.texture('top', 'create_compressed:block/cogwheel_block')
		.texture('side', 'create_compressed:block/andesite_crate')
		.texture('bottom', 'create_compressed:block/andesite_crate')
		.mapColor('WOOD')
		.displayName('Cogwheel Crate')
		.woodSoundType()
		.resistance(6)
		.hardness(1.5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/axe')
		.tagBlock('minecraft:mineable/pickaxe')
	event.create('large_cogwheel_block')
		.parentModel('minecraft:block/cube_bottom_top')
		.texture('top', 'create_compressed:block/large_cogwheel_block')
		.texture('side', 'create_compressed:block/andesite_crate')
		.texture('bottom', 'create_compressed:block/andesite_crate')
		.mapColor('WOOD')
		.displayName('Large Cogwheel Crate')
		.woodSoundType()
		.resistance(6)
		.hardness(1.5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/axe')
		.tagBlock('minecraft:mineable/pickaxe')
	event.create('belt_block')
		.parentModel('minecraft:block/cube_bottom_top')
		.texture('top', 'create_compressed:block/belt_block')
		.texture('side', 'create_compressed:block/andesite_crate')
		.texture('bottom', 'create_compressed:block/andesite_crate')
		.mapColor('WOOD')
		.displayName('Mechanical Belt Crate')
		.woodSoundType()
		.resistance(6)
		.hardness(1.5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/axe')
		.tagBlock('minecraft:mineable/pickaxe')

	// stone
	event.create('shaft_block')
		.mapColor('STONE')
		.displayName('Shaft Bundle')
		.stoneSoundType()
		.resistance(6)
		.hardness(1.5)
		.requiresTool()
		.property(BlockProperties.AXIS)
		.placementState(event => event.set(BlockProperties.AXIS, event.clickedFace.axis))
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/pickaxe')

	// lantern
	event.create('precision_mechanism_block')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/mechanism_block')
		.mapColor('TERRACOTTA_YELLOW')
		.displayName('Block of Precision Mechanism')
		.soundType('lantern')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')

	// sand
	event.create('cinder_flour_block', 'falling')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/cinder_flour_pile')
		.mapColor('NETHER')
		.displayName('Pile of Cinder Flour')
		.sandSoundType()
		.resistance(0.4)
		.hardness(0.4)
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:infiniburn_end')
		.tagBlock('minecraft:infiniburn_nether')
		.tagBlock('minecraft:infiniburn_overworld')
	event.create('powdered_obsidian_block', 'falling')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/powdered_obsidian_pile')
		.mapColor('COLOR_BLACK')
		.displayName('Pile of Powdered Obsidian')
		.sandSoundType()
		.resistance(1200)
		.hardness(50)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:needs_diamond_tool')
	event.create('wheat_flour_block', 'falling')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/wheat_flour_pile')
		.mapColor('SAND')
		.displayName('Pile of Wheat Flour')
		.sandSoundType()
		.resistance(0.5)
		.hardness(0.5)
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')

	// netherite_block
	event.create('copper_sheet_block')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/copper_sheet_block')
		.mapColor('COLOR_ORANGE')
		.displayName('Block of Copper Sheet')
		.soundType('netherite_block')
		.resistance(6)
		.hardness(3)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
	event.create('iron_sheet_block')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/iron_sheet_block')
		.mapColor('METAL')
		.displayName('Block of Iron Sheet')
		.soundType('netherite_block')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
	event.create('golden_sheet_block')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/gold_sheet_block')
		.mapColor('GOLD')
		.displayName('Block of Gold Sheet')
		.soundType('netherite_block')
		.resistance(6)
		.hardness(3)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
	event.create('brass_sheet_block')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/brass_sheet_block')
		.mapColor('TERRACOTTA_YELLOW')
		.displayName('Block of Brass Sheet')
		.soundType('netherite_block')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')

	// basalt
	event.create('crushed_raw_copper_block', 'falling')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/crushed_copper_pile')
		.mapColor('COLOR_ORANGE')
		.displayName('Pile of Crushed Raw Copper')
		.soundType('basalt')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
	event.create('crushed_raw_iron_block', 'falling')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/crushed_iron_pile')
		.mapColor('RAW_IRON')
		.displayName('Pile of Crushed Raw Iron')
		.soundType('basalt')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_stone_tool')
	event.create('crushed_raw_gold_block', 'falling')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/crushed_gold_pile')
		.mapColor('GOLD')
		.displayName('Pile of Crushed Raw Gold')
		.soundType('basalt')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
	event.create('crushed_raw_zinc_block', 'falling')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/crushed_zinc_pile')
		.mapColor('GLOW_LICHEN')
		.displayName('Pile of Crushed Raw Zinc')
		.soundType('basalt')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
	event.create('crushed_raw_tin_block', 'falling')
		.mapColor('QUARTZ')
		.displayName('Pile of Crushed Raw Tin')
		.soundType('basalt')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
	event.create('crushed_raw_arkenium_block', 'falling')
		.mapColor('COLOR_BLACK')
		.displayName('Pile of Crushed Raw Arkenium')
		.soundType('basalt')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_iron_tool')
	/* event.create('crushed_ancient_debris_block', 'falling')
		.mapColor('COLOR_BLACK')
		.displayName('Pile of Crushed Ancient Debris')
		.soundType('basalt')
		.resistance(6)
		.hardness(5)
		.requiresTool()
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/shovel')
		.tagBlock('minecraft:mineable/pickaxe')
		.tagBlock('minecraft:needs_diamond_tool') */

	// slime_block
	event.create('wheat_dough_block')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/dough_block')
		.mapColor('SAND')
		.displayName('Block of Wheat Dough')
		.soundType('slime_block')
		.resistance(0.1)
		.hardness(0.1)
		.bounciness(0.5)
		.speedFactor(0.5)
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/hoe')

	// azalea_leaves
	event.create('pulp_block')
		.parentModel('minecraft:block/cube_all')
		.texture('all', 'create_compressed:block/pulp_block')
		.mapColor('TERRACOTTA_LIGHT_GRAY')
		.displayName('Block of Pulp')
		.soundType('azalea_leaves')
		.resistance(0.3)
		.hardness(0.3)
		.tag('c:storage_blocks')
		.tagBlock('minecraft:mineable/hoe')

	//createdelight
	function filledCrate(name, mapcolor, light) {
		var crate = name + ' Crate'
		var type = name.replace(' ', '_').toLowerCase() + '_crate'
		switch (crate) {
			case 'Raw Cod Crate': {
				type = 'cod_crate'
				break
			}
			case 'Raw Salmon Crate': {
				type = 'salmon_crate'
				break
			}
		}
		var tex = type
		switch (type) {
			case 'sweet_berry_crate': {
				tex = 'berry_crate'
				break
			}
			case 'glow_berry_crate': {
				tex = 'glowberry_crate'
				break
			}
		}
		event.create(type)
			.parentModel('minecraft:block/cube_bottom_top')
			.texture('top', 'cratedelight:block/' + tex + '_top')
			.texture('side', 'cratedelight:block/' + tex + '_side')
			.texture('bottom', 'farmersdelight:block/crate_bottom')
			.mapColor(mapcolor)
			.displayName(crate)
			.woodSoundType()
			.resistance(3)
			.hardness(2)
			.lightLevel(light ? light : 0)
			.tag('c:storage_blocks')
			.tagBlock('minecraft:mineable/axe')
	}
	function filledBag(type, mapcolor, display) {
		var tex = type
		if (type == 'cocoa_beans') { tex = 'cocoabeans' }
		event.create(type + '_bag')
			.parentModel('minecraft:block/cube')
			.texture('up', 'cratedelight:block/' + tex + '_bag_top')
			.texture('north', 'farmersdelight:block/rice_bag_side_tied')
			.texture('east', 'farmersdelight:block/rice_bag_side')
			.texture('south', 'farmersdelight:block/rice_bag_side_tied')
			.texture('west', 'farmersdelight:block/rice_bag_side')
			.texture('down', 'farmersdelight:block/rice_bag_bottom')
			.texture('particle', '#up')
			.mapColor(mapcolor)
			.displayName(display)
			.soundType('wool')
			.tag('c:storage_blocks')
			.tagBlock('farmersdelight:mineable/knife')
	}
	filledCrate('Apple', 'WOOD')
	filledCrate('Golden Apple', 'WOOD')
	filledCrate('Sweet Berry', 'WOOD')
	filledCrate('Glow Berry', 'WOOD', 0.93)
	filledCrate('Golden Carrot', 'WOOD')
	filledCrate('Raw Cod', 'WOOD')
	filledCrate('Raw Salmon', 'WOOD')
	filledCrate('Egg', 'WOOD')
	filledCrate('Brown Mushroom', 'WOOD')
	filledCrate('Red Mushroom', 'WOOD')
	filledBag('cookie', 'WOOD', 'Bag of Cookies')
	filledBag('cocoa_beans', 'WOOD', 'Bag of Cocoa Beans')
	filledBag('sugar', 'WOOD', 'Bag of Sugar')
	filledBag('gunpowder', 'WOOD', 'Bag of Gunpowder')
	filledBag('wheat_flour', 'WOOD', 'Bag of Wheat Flour')
	filledBag('cinder_flour', 'WOOD', 'Bag of Cinder Flour')
	filledBag('powdered_obsidian', 'WOOD', 'Bag of Powdered Obsidian')

	//farmers-deco
	function createEmptyCrate(type) {
		event.create(type)
			.mapColor('WOOD')
			.woodSoundType()
			.fullBlock(false)
			.box(0, 2, 0, 2, 16, 2)
			.box(2, 14, 0, 14, 16, 2)
			.box(14, 2, 0, 16, 16, 2)
			.box(14, 14, 2, 16, 16, 14)
			.box(14, 2, 14, 16, 16, 16)
			.box(2, 14, 14, 14, 16, 16)
			.box(0, 2, 14, 2, 16, 16)
			.box(0, 14, 2, 2, 16, 14)
			.box(2, 10, 0, 14, 12, 2)
			.box(2, 6, 0, 14, 8, 2)
			.box(2, 2, 0, 14, 4, 2)
			.box(14, 10, 2, 16, 12, 14)
			.box(14, 6, 2, 16, 8, 14)
			.box(14, 2, 2, 16, 4, 14)
			.box(2, 10, 14, 14, 12, 16)
			.box(2, 6, 14, 14, 8, 16)
			.box(2, 2, 14, 14, 4, 16)
			.box(0, 10, 2, 2, 12, 14)
			.box(0, 6, 2, 2, 8, 14)
			.box(0, 2, 2, 2, 4, 14)
			.box(0, 0, 0, 16, 2, 16)
			.tagBlock('minecraft:mineable/axe')
	}
	createEmptyCrate('empty_crate')
	createEmptyCrate('skyroot_empty_crate')
	event.create('empty_bag')
		.mapColor('WOOD')
		.soundType('wool')
		.fullBlock(false)
		.box(2, 0, 2, 14, 12, 14)
		.box(3, 12, 3, 13, 14, 13)
		.tagBlock('farmersdelight:mineable/knife')

	//vents
	/* event.create('vent_i')
		.property(BlockProperties.AXIS)
		.placementState(event => event.set(BlockProperties.AXIS, event.clickedFace.axis))
		.soundType('metal')
		.displayName('Vent |')
		.fullBlock(false)
		.box(0, 0, 0, 16, 16, 1)
		.box(0, 0, 1, 1, 16, 15)
		.box(15, 0, 1, 16, 16, 15)
		.box(0, 0, 15, 16, 16, 16)
		.tagBlock('mineable/pickaxe') */
})

StartupEvents.registry('item', event => {
	event.create('pet').displayName('Eggo').texture('kubejs:item/eggo')

	event.create('netherite_chunk').fireResistant()
	event.create('netherite_nugget')
		.fireResistant()
		.tag('c:nuggets')
		.tag('c:nuggets/netherite')

	/* event.create('crushed_ancient_debris')
		.fireResistant()
		.tag('create:crushed_raw_materials') */
	event.create('crushed_raw_arkenium')
		.tag('create:crushed_raw_materials')

	event.create('flashing_bark')
		.tag('farmersdelight:barks')
		.tag('arsdelight:barks')

	function grabProgress(str) {
		const match = str.match(/\d+\.\d+/)
		return match ? Number(match[0]) : null
	}
	function createIncomplete(name, override_display) {
		if (override_display) {
			event.create(name)
				.unstackable()
				.displayName(override_display)
				.barWidth(itemstack => itemstack.components.has('create:sequenced_assembly') ? Math.round(grabProgress(itemstack.components.get('create:sequenced_assembly').toString()) * 13) : 0)
		} else {
			event.create(name)
				.unstackable()
				.barWidth(itemstack => itemstack.components.has('create:sequenced_assembly') ? Math.round(grabProgress(itemstack.components.get('create:sequenced_assembly').toString()) * 13) : 0)
			/* .barColor(itemstack => {
				let colors = [
					0xFFC175,
					0xF0C67E,
					0xE0CB87,
					0xD1D190,
					0xC2D699,
					0xB2DBA2,
					0xA3E0AB,
					0x94E5B3,
					0x84EABC,
					0x75F0C5,
					0x66F5CE,
					0x56FAD7,
					0x47FFE0
					]
					return colors[itemstack.components.has('create:sequenced_assembly') ? Math.round(grabProgress(itemstack.components.get('create:sequenced_assembly').toString()) * 13) : 0]
					}) */
		}
	}
	event.create('backpack_thread').maxStackSize(8)
	event.create('needle')
	event.create('copper_backpack_thread').unstackable()
	event.create('iron_backpack_thread').unstackable()
	event.create('gold_backpack_thread').unstackable()
	event.create('diamond_backpack_thread').unstackable()
	event.create('netherite_needle').fireResistant()
	event.create('netherite_backpack_thread').unstackable().fireResistant()

	event.create('andesite_zinc_frame').maxStackSize(16)
	event.create('netherite_anvil').fireResistant()

	function createSandpaper(type) {
		event.create(type + '_sand_paper')
			.texture('createsandpapers:item/' + type + '_sand_paper')
			.unstackable()
			.maxDamage(8)
			.tag('create:sandpaper')
	}
	createSandpaper('white')
	createSandpaper('orange')
	createSandpaper('black')

	createIncomplete('incomplete_advanced_deposit_upgrade')
	createIncomplete('incomplete_advanced_feeding_upgrade')
	createIncomplete('incomplete_advanced_filter_upgrade')
	createIncomplete('incomplete_advanced_jukebox_upgrade')
	createIncomplete('incomplete_advanced_magnet_upgrade')
	createIncomplete('incomplete_advanced_pickup_upgrade')
	createIncomplete('incomplete_advanced_pump_upgrade')
	createIncomplete('incomplete_advanced_refill_upgrade')
	createIncomplete('incomplete_advanced_restock_upgrade')
	createIncomplete('incomplete_advanced_tool_swapper_upgrade')
	createIncomplete('incomplete_advanced_void_upgrade')
	createIncomplete('incomplete_anvil_upgrade')
	createIncomplete('incomplete_auto_blasting_upgrade', 'Incomplete Auto-Blasting Upgrade')
	createIncomplete('incomplete_auto_smelting_upgrade', 'Incomplete Auto-Smelting Upgrade')
	createIncomplete('incomplete_auto_smoking_upgrade', 'Incomplete Auto-Smoking Upgrade')
	createIncomplete('incomplete_blasting_upgrade')
	createIncomplete('incomplete_compacting_upgrade')
	createIncomplete('incomplete_crafting_upgrade')
	createIncomplete('incomplete_everlasting_upgrade')
	createIncomplete('incomplete_feeding_upgrade')
	createIncomplete('incomplete_filter_upgrade')
	createIncomplete('incomplete_jukebox_upgrade')
	createIncomplete('incomplete_netherite_anvil')
	createIncomplete('incomplete_pump_upgrade')
	createIncomplete('incomplete_sawmill_upgrade')
	createIncomplete('incomplete_smelting_upgrade')
	createIncomplete('incomplete_smithing_upgrade')
	createIncomplete('incomplete_smoking_upgrade')
	createIncomplete('incomplete_stonecutter_upgrade')
	createIncomplete('incomplete_tank_upgrade')
	createIncomplete('incomplete_tool_swapper_upgrade')
	createIncomplete('incomplete_upgrade_base')
})

StartupEvents.registry('fluid', event => {
	event.create('molten_netherite', 'thick')
		.tint(0xFFFFFF)
		.stillTexture('kubejs:block/molten_netherite')
		.flowingTexture('kubejs:block/molten_netherite_flowing')
		.noBlock()
		.noBucket()
})